"""
Provenance & Digital Watermark Analyzer
Checks C2PA/Content Credentials, perceptual hash chains, and steganographic watermarks.
"""
import logging
import hashlib
import io
import struct
from pathlib import Path
from typing import Dict, Any, Union, Optional, List
from PIL import Image

logger = logging.getLogger("ai_forensics.provenance")

# C2PA JUMBF UUID (ISO 19566-5) — present in Content Credentials images
C2PA_JUMBF_UUID = b"\x63\x32\x70\x61"  # 'c2pa' marker in JUMBF box


def _compute_phash(img: Image.Image, hash_size: int = 16) -> str:
    """Perceptual hash (pHash) for content fingerprinting."""
    img_gray = img.convert("L").resize((hash_size, hash_size), Image.LANCZOS)
    pixels = list(img_gray.getdata())
    avg = sum(pixels) / len(pixels)
    bits = "".join("1" if p >= avg else "0" for p in pixels)
    hex_hash = hex(int(bits, 2))[2:].zfill(hash_size * hash_size // 4)
    return hex_hash


def _hamming_distance(hash1: str, hash2: str) -> int:
    """Hamming distance between two hex pHash strings."""
    if len(hash1) != len(hash2):
        return -1
    b1 = bin(int(hash1, 16))[2:].zfill(len(hash1) * 4)
    b2 = bin(int(hash2, 16))[2:].zfill(len(hash2) * 4)
    return sum(c1 != c2 for c1, c2 in zip(b1, b2))


def _check_c2pa_jumbf(raw_bytes: bytes) -> Dict[str, Any]:
    """
    Scans JPEG/JPEG 2000 bytes for C2PA JUMBF box presence.
    Returns detection result and basic metadata.
    """
    result = {
        "c2pa_present": False,
        "c2pa_version": None,
        "content_credentials_claimed": False,
    }
    try:
        idx = raw_bytes.find(C2PA_JUMBF_UUID)
        if idx != -1:
            result["c2pa_present"] = True
            result["content_credentials_claimed"] = True
            # Try to read version byte if present
            if idx + 8 < len(raw_bytes):
                result["c2pa_version"] = hex(raw_bytes[idx + 4])
    except Exception:
        pass
    return result


def _check_png_text_chunks(img: Image.Image) -> List[str]:
    """Extract tEXt/iTXt chunks from PNG that may indicate AI generation."""
    chunks = []
    try:
        info = img.info or {}
        for k, v in info.items():
            chunks.append(f"{k}={str(v)[:120]}")
    except Exception:
        pass
    return chunks


def _compute_md5_sha256(raw_bytes: bytes) -> Dict[str, str]:
    return {
        "md5": hashlib.md5(raw_bytes).hexdigest(),
        "sha256": hashlib.sha256(raw_bytes).hexdigest(),
    }


def analyze_provenance(image_path: str) -> Dict[str, Any]:
    """
    Full provenance analysis: C2PA, pHash, text chunks, cryptographic fingerprints.

    Returns:
        - phash: perceptual hash for deduplication/chain comparison
        - md5 / sha256: cryptographic fingerprints
        - c2pa_present: whether Content Credentials are embedded
        - content_credentials_claimed: C2PA assertion
        - png_text_chunks: any tEXt/iTXt chunks (often AI metadata)
        - ai_generation_claimed: if text chunks claim AI origin
        - synthetic_probability: provenance-based heuristic
    """
    try:
        with open(image_path, "rb") as f:
            raw_bytes = f.read()

        img = Image.open(io.BytesIO(raw_bytes))
        phash = _compute_phash(img)
        hashes = _compute_md5_sha256(raw_bytes)
        c2pa_info = _check_c2pa_jumbf(raw_bytes)
        png_chunks = _check_png_text_chunks(img)

        # Check for AI generation claims in PNG metadata
        ai_keywords = ["stable-diffusion", "midjourney", "dall-e", "ai-generated", "generated by", "comfyui", "a1111"]
        chunks_lower = " ".join(png_chunks).lower()
        ai_generation_claimed = any(kw in chunks_lower for kw in ai_keywords)

        suspicious_flags = []
        if ai_generation_claimed:
            suspicious_flags.append("ai_generation_metadata_present")
        if not c2pa_info["c2pa_present"]:
            suspicious_flags.append("no_content_credentials")

        # Provenance alone can't reliably predict synthetic probability
        # But missing C2PA + AI claims = significant signal
        base_score = 0.1  # neutral baseline
        if ai_generation_claimed:
            base_score += 0.85
        if not c2pa_info["c2pa_present"]:
            base_score += 0.1  # mild negative signal (most real photos also lack C2PA currently)

        synthetic_probability = min(1.0, base_score)

        return {
            "phash": phash,
            **hashes,
            **c2pa_info,
            "png_text_chunks": png_chunks[:10],  # limit to 10
            "ai_generation_claimed": ai_generation_claimed,
            "suspicious_flags": suspicious_flags,
            "synthetic_probability": round(synthetic_probability, 4),
            "analysis": "provenance",
            "status": "success",
        }

    except Exception as e:
        logger.error(f"Provenance analysis failed: {e}", exc_info=True)
        return {
            "phash": None,
            "md5": None,
            "sha256": None,
            "c2pa_present": False,
            "content_credentials_claimed": False,
            "png_text_chunks": [],
            "ai_generation_claimed": False,
            "suspicious_flags": ["analysis_error"],
            "synthetic_probability": 0.5,
            "analysis": "provenance",
            "status": "error",
            "error": str(e),
        }
